name: Build third library package

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'OS version: ubuntu:20.04, ubuntu:22.04, centos:7 or centos:8'
        required: true
        default: 'ubuntu:20.04'
      spark:
        description: 'Spark version: spark-3.2, spark-3.3, spark-3.4 or spark-3.5'
        required: true
        default: 'spark-3.5'
      hadoop:
        description: 'Hadoop version: 2.7.4, 3.2.0, 3.2.2, 3.3.1, 3.3.3 or 3.3.6'
        required: true
        default: '3.3.3'

jobs:
  build-script-test:
    runs-on: ubuntu-20.04
    container: centos:8
    steps:
      - uses: actions/checkout@v4
      - name: Build third library package
        run: |
          sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-* || true && \
          sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-* || true && \
          dnf install -y epel-release sudo && \
          yum install -y dnf-plugins-core && \
          yum config-manager --set-enabled powertools && \
          dnf --enablerepo=powertools install -y ninja-build && \
          dnf --enablerepo=powertools install -y libdwarf-devel && \
          dnf install -y --setopt=install_weak_deps=False ccache gcc-toolset-9 git wget which libevent-devel && \
          openssl-devel re2-devel libzstd-devel lz4-devel double-conversion-devel && \
          curl-devel cmake libicu-devel && \
          source /opt/rh/gcc-toolset-9/enable || exit 1 && \
          yum install -y java-1.8.0-openjdk-devel patch && \
          export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk && \
          export PATH=$JAVA_HOME/bin:$PATH && \
          wget https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz && \
          tar -xvf apache-maven-3.8.8-bin.tar.gz && \
          mv apache-maven-3.8.8 /usr/lib/maven && \
          export MAVEN_HOME=/usr/lib/maven && \
          export PATH=${PATH}:${MAVEN_HOME}/bin && \
          source /env.sh && \
          cd $GITHUB_WORKSPACE/ && \
          ./dev/package.sh
      - name: Upload bundle package
        uses: actions/upload-artifact@v2
        with:
          name: gluten-third-library-package
          path: package/target/thirdparty-lib/gluten-thirdparty-lib-*.jar
          retention-days: 7